### ISSUE TITLE
Expose `guid()` as New-AzGuid

### ISSUE THREAD

**Issue by matsest** [SimonWahlin/AzExpression#1]
Did not know about this module before, so awesome to see this implemented - I've missed this functionality in pwsh when using these deterministic functions. Great work!

Would you allow a PR for a new command/function here? (I've started something to verify the functionality in a [fork](https://github.com/matsest/AzExpression/tree/feat/az-guid))

I also have some questions about how the DLLs are handled/updated, would be good for transparency if these were also handled by a script using public sources.

**Comment by SimonWahlin** [comment]
I would absolutely appreciate a PR! Sounds like a great idea!

Transparency is good, I'll look at setting up a build pipeline that downloads the dlls, build the module and publish it to gallery.
